name: Deploy .NET Core to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # IMPORTANT (your IIS machine)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o C:\deploy\opsatm

    - name: Stop IIS
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "opsatm-backend"

    - name: Copy Files
      run: |
        xcopy C:\deploy\opsatm C:\inetpub\wwwroot\opsatm /E /Y

    - name: Start IIS
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "opsatm-backend"
